# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(587, 581)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.file_viewer = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.file_viewer.setGeometry(QtCore.QRect(20, 10, 171, 261))
        self.file_viewer.setObjectName("file_viewer")
        self.file_select_button = QtWidgets.QPushButton(self.centralwidget)
        self.file_select_button.setGeometry(QtCore.QRect(20, 280, 113, 32))
        self.file_select_button.setObjectName("file_select_button")
        self.img_viewer = QtWidgets.QGraphicsView(self.centralwidget)
        self.img_viewer.setGeometry(QtCore.QRect(210, 80, 361, 191))
        self.img_viewer.setObjectName("img_viewer")
        self.model_upload = QtWidgets.QPushButton(self.centralwidget)
        self.model_upload.setGeometry(QtCore.QRect(210, 280, 113, 32))
        self.model_upload.setObjectName("model_upload")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(210, 10, 361, 61))
        self.graphicsView.setObjectName("graphicsView")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(210, 310, 361, 171))
        self.textEdit_2.setObjectName("textEdit_2")
        self.code_list = QtWidgets.QListWidget(self.centralwidget)
        self.code_list.setGeometry(QtCore.QRect(20, 310, 171, 171))
        self.code_list.setObjectName("code_list")
        item = QtWidgets.QListWidgetItem()
        self.code_list.addItem(item)
        self.code_input_box = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.code_input_box.setGeometry(QtCore.QRect(20, 490, 131, 21))
        self.code_input_box.setObjectName("code_input_box")
        self.add_code_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_code_button.setGeometry(QtCore.QRect(160, 490, 113, 21))
        self.add_code_button.setObjectName("add_code_button")
        self.tag_it_button = QtWidgets.QPushButton(self.centralwidget)
        self.tag_it_button.setGeometry(QtCore.QRect(130, 280, 61, 32))
        self.tag_it_button.setObjectName("tag_it_button")
        self.new_memo_button = QtWidgets.QPushButton(self.centralwidget)
        self.new_memo_button.setGeometry(QtCore.QRect(350, 480, 113, 21))
        self.new_memo_button.setObjectName("new_memo_button")
        self.save_memo_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_memo_button.setGeometry(QtCore.QRect(460, 480, 113, 21))
        self.save_memo_button.setObjectName("save_memo_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 587, 22))
        self.menubar.setObjectName("menubar")
        self.menuTest2 = QtWidgets.QMenu(self.menubar)
        self.menuTest2.setObjectName("menuTest2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuTest2.addSeparator()
        self.menubar.addAction(self.menuTest2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.file_select_button.setText(_translate("MainWindow", "upload_txt"))
        self.model_upload.setText(_translate("MainWindow", "model_upload"))
        __sortingEnabled = self.code_list.isSortingEnabled()
        self.code_list.setSortingEnabled(False)
        item = self.code_list.item(0)
        item.setText(_translate("MainWindow", "test_code"))
        self.code_list.setSortingEnabled(__sortingEnabled)
        self.add_code_button.setText(_translate("MainWindow", "add code"))
        self.tag_it_button.setText(_translate("MainWindow", "tag_it"))
        self.new_memo_button.setText(_translate("MainWindow", "new memo"))
        self.save_memo_button.setText(_translate("MainWindow", "save memo"))
        self.menuTest2.setTitle(_translate("MainWindow", "Test2"))
